//* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//    1,2,3,5,8,13,21,34,55,89...
//   By considering the terms, find the sum of the even-valued terms
//
//   For these terms the sum will be 231
//
//

function fiboSumEven(numberOfTerms) {
  function helper(n, a, b, sum) {
    if (n <= 0) {
      return sum;
    }
    if (sum > 4000000) {
      console.log("Exceeded limit");
      return sum;
    }
    let nextValue = a + b;
    if (nextValue % 2 == 0) {
      sum += nextValue;
    }
    return helper(n - 1, b, nextValue, sum);
  }
  if (numberOfTerms <= 0) {
    return 0;
  }
  if (numberOfTerms == 1) {
    return 0;
  }
  if (numberOfTerms == 2) {
    return 2;
  }
  return helper(numberOfTerms - 2, 1, 2, 2);
}

console.log(fiboSumEven(40));
